### PR TITLE
FIX: priv map should be case-insensitive

### PR DESCRIPTION
**Pull request by xuanyu66**
### What problem does this PR solve? 

image
Fix the test failure when TiDB returns the lower-case privilege's name.

### What is changed and how it works?

make the privilege map case-insensitive

### Check List 

Tests 

 - Unit test

Related changes

### CODE REVIEW

**Comment by xuanyu66** [comment]
/run-all-tests tikv=release-4.0 tidb=release-4.0 pd=release-4.0

**Comment by xuanyu66** [comment]
@sunxiaoguang @birdstorm PTAL

**Review by sunxiaoguang — APPROVED** [review]

**Pull request merged**
