### PR TITLE
upgrade protobuf

### PR DESCRIPTION
**Pull request by marsishandsome**
升级protobuf

### CODE REVIEW

**Comment by zhexuany** [comment]
Should we directly merge this into master? @ilovesoup

**Comment by birdstorm** [comment]
@zhexuany I think it might conflict with #598 if we merge this directly into master.

**Comment by zhexuany** [comment]
I see the PR is labeled with DNM. We can merge this first and rebase #598

**Comment by birdstorm** [comment]
> I see the PR is labeled with DNM. We can merge this first and rebase #598

agree

**Comment by HelloMin** [comment]
mars脑残粉来顶了！疯狂打电话！！

**Pull request merged**
