### PR TITLE
release 2.2.0-rc1

### PR DESCRIPTION
**Pull request by marsishandsome**
### What problem does this PR solve? 
1. change defaule value of `spark.tispark.write.enable` to `true`
2. update document
3. move examples to https://github.com/pingcap/tispark-test/tree/master/tispark-examples
4. enable missing test in TiBatchWriteSuite

close https://github.com/pingcap/tispark/issues/919

### CODE REVIEW

**Comment by marsishandsome** [comment]
@zhexuany @birdstorm PTAL

**Comment by birdstorm** [comment]
should we modify the version number?

**Pull request merged**
