### PR TITLE
add stale action

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve? 
Manage inactive issues
- open for 30 days with no activity will be stale
- stale for 14 days with no activity will be closed

The issue with `type/feature-request`,`type/enhancement` will not be affected.

You can also exclude an issue  by the command `/lifecycle frozen`

### CODE REVIEW

**Comment by shiyuhang0** [comment]
PTAL @zhangyangyu @birdstorm @xuanyu66

**Review by xuanyu66 — APPROVED** [review]

**Review by birdstorm — APPROVED** [review]
LGTM

**Pull request merged**
