### PR TITLE
Support enum and set in test generation

### LINKED ISSUE #946: Support ENUM and SET type for test generators
**Is your feature request related to a problem? Please describe.**
To support ENUM and SET types in test data generator.

### PR DESCRIPTION
**Pull request by birdstorm**
### What problem does this PR solve? 

Close #946 

Support enum and set in generation. You can set `isRandomEnumValue=false` in `ColumnValueGenerator` to generate random enum/set values. By default, the enum value will be `"XS", "S", "M", "L", "XL", "XXL"`

Needs to be cherry-picked to release-2.1 for better testing experience.

### CODE REVIEW

**Comment by zhexuany** [comment]
@birdstorm It will be awesome if you can state how do you implement it.

**Comment by birdstorm** [comment]
> @birdstorm It will be awesome if you can state how do you implement it.

@zhexuany description updated.

**Pull request merged**
