### PR TITLE
[Trivial]Don't let null constant push down

### PR DESCRIPTION
**Pull request by Novemser**
`TiConstant` don't support `null` type currently, we don't allow null constant push down as a trivial fix before a satisfactory solution.

### CODE REVIEW

**Comment by birdstorm** [comment]
should fix #98

**Comment by Novemser** [comment]
Since any SQL condition match `col != null` or `col == null` will cause the problem, label it as `p0`.

**Comment by Novemser** [comment]
PTAL @ilovesoup

**Comment by ilovesoup** [comment]
@Novemser Please resolve conflict.

**Comment by ilovesoup** [comment]
@Novemser please resolve conflict.

**Pull request merged**
