### PR TITLE
Fix enum with trailing spaces

### LINKED ISSUE #1765: [BUG] test fail with tidb-5.0 Test enum with trailing spaces
https://github.com/pingcap/tispark/pull/1762/files

image

### PR DESCRIPTION
**Pull request by birdstorm**
Close #1765

### CODE REVIEW

**Review by marsishandsome — APPROVED** [review]
LGTM

**Comment by birdstorm** [comment]
/run-all-tests pd=release-5.1 tidb=release-5.1 tikv=release-5.1

**Pull request merged**
