### PR TITLE
Add agg mode to fix read tifalsh fail

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve? 

reproduce step:

1. create table test.t(id int not null);
2. alter table test.t set tiflash replica 1;
3. Execute tispark
```
spark.conf.set("spark.tispark.isolation_read_engines", "tiflash")
spark.sql("select max(id) from tidb_catalog.test.t").show()
```
4. output error

```
can not convert NULL value to non-Nullable type
```

### What is changed and how it works?

update tipb proto and set AggFunctionMode to Partial1Mode

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Review by windtalker — APPROVED** [review]
lgtm

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-6.5 tikv=release-6.5 pd=release-6.5

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-6.5 tikv=release-6.5 pd=release-6.5

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-6.5 tikv=release-6.5 pd=release-6.5

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-6.5 tikv=release-6.5 pd=release-6.5

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-6.5 tikv=release-6.5 pd=release-6.5

**Pull request merged**
