### PR TITLE
[close #2376]Fix bug any thrown exception or error reaching the executor causes the executor to halt

### LINKED ISSUE #2376: [BUG] TLS reload don't work after delete cert file
**Describe the bug**

After deleting the cert file, the TLS reload will be invalidation.
If using delete in reload operator, such as delete old cert first then create a new cert, we will meet a mistake that the reloading didn't work. 

**What did you do**
1. use correct cert first, everything looks normal.
```
scala> spark.sql("show databases").show
+--------------------+
|           namespace|
+--------------------+
|   tispark_test_auth|
|        tispark_test|
|                test|
|tispark_test_auth...|
|    resolvelock_test|
|           tpch_test|
|               mysql|
|                tpcc|
+--------------------+

```

2. delete cert, I can see the TiSpark has detected change but it still use the old TLS channel.
```
# delete cert
sudo rm client.pem

# tispark detects change but nothing changes. TiSpark should not work without cert.
scala> 22/06/13 18:36:04 WARN ChannelFactory$CertWatcher: detected ssl context changes: /config/cert/pem/client.pem

scala> spark.sql("show databases").show
22/06/13 18:37:06 INFO TiUtil$: spark.tispark.stale_read = 
22/06/13 18:37:06 INFO TiUtil$: spark.tispark.stale_read = 
22/06/13 18:37:06 INFO TiUtil$: spark.tispark.stale_read = 
22/06/13 18:37:06 INFO TiUtil$: spark.tispark.stale_read = 
22/06/13 18:37:06 INFO TiUtil$: spark.tispark.stale_read = 
+--------------------+
|           namespace|
+--------------------+
|   tispark_test_auth|
|        tispark_test|
|                test|
|tispark_test_auth...|
|    resolvelock_test|
|           tpch_test|
|               mysql|
|                tpcc|
+--------------------+
```

3. add a new cert and nothing happens. TiSpark can not detect cert file change!
```
# cp a new cert
sudo cp ~/IdeaProject/tispark/config/cert/pem/client.pem ./

# nothing is detected is Spark-shell
scala>
```

**What do you expect**
When I delete the cert, Spark should not work.
When I create a new cert, Spark should detect and build a new channel.

**Spark and TiSpark version info**
Spark version: 3.2.0
TiSpark version: 3.0.0

### PR DESCRIPTION
**Pull request by Daemonxiao**
### What problem does this PR solve? 
To close #2376.

### What is changed and how it works?
Add try-catch in tryReload().
tryReload() is used as a task in ScheduledFuture. When tryReload() throws an exception, the schedule will be suppressed which makes tryReload() will not work.
So we need try-catch in tryReload().
```
    // If any execution of the task encounters an exception, subsequent executions are suppressed.
    private void tryReload() {
      // Add exception handling to avoid schedule stop.
      try {
        if (needReload()) {
          onChange.run();
        }
      } catch (Exception e) {
        logger.error("Failed to reload cert!" + e);
      }
    }
```

### Why did this bug happen?
TiSpark uses the last modified time to watch whether the cert file is changed or not.
When you deleted the cert file, TiSpark detected this change and try to reload the cert and build a new SslContextBuilder with a file that has been deleted. Then error happened.
What we should do is make the schedule keep working when tryReload failed.

```
    public SslContextBuilder createSslContextBuilder() {
      SslContextBuilder builder = GrpcSslContexts.forClient().protocols("TLSv1.2", "TLSv1.3");
      try {
        if (trustPath != null) {
          builder.trustManager(new File(trustPath));                     // error would happen here when use a file that has been deleted
        }
        if (chainPath != null && keyPath != null) {
          builder.keyManager(new File(chainPath), new File(keyPath));    // error would happen here when use a file that has been deleted
        }
      } catch (Exception e) {
        logger.error("PEM SSL context builder failed!", e);
        throw new IllegalArgumentException(e);
      }
      return builder;
    }
```

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Side effects

 - Possible performance regression

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Review by shiyuhang0 — APPROVED** [review]

**Review by xuanyu66 — APPROVED** [review]

**Comment by xuanyu66** [comment]
Maybe change the PR name to `Fix bug any thrown exception or error reaching the executor causes the executor to halt`

**Pull request merged**
