### PR TITLE
use `df.limit(1).count`  instead of `df.count` to express `df.isEmpty`

### LINKED ISSUE #1228: use `df.isEmpty` insteadof `count`
https://github.com/pingcap/tispark/blob/927cacf07c0c80fe3dedb5c6415cc790c4f9750d/core/src/main/scala/com/pingcap/tispark/TiBatchWrite.scala#L144

use `df.isEmpty` insteadof `count`

### PR DESCRIPTION
**Pull request by wfnuser**
### What problem does this PR solve? 
Close #1228

### What is changed and how it works?
implement a dataset empty check util function; and use it instead of checking it by `df.count() == 0` to improve the performance

### Check List 

Tests 

 - Integration test

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by birdstorm** [comment]
@wfnuser hi, please sign your CLA license.

**Comment by wfnuser** [comment]
> @wfnuser hi, please sign your CLA license.

@birdstorm done.

**Comment by birdstorm** [comment]
nice work! 

I'm also wondering whether `df.head().isEmpty()` may be faster? Is there any benchmark on this?

**Pull request merged**
