### PR TITLE
fix parition table isn't shown in show command

### LINKED ISSUE #1330: table with partition cannot be showed correctly in thrift-server
spark 2.4.4 thrift server 通过spark.sql.extensions org.apache.spark.sql.TiExtens 添加tispark，执行一下语句：
```
show table extended like 'test_users_dt' PARTITION (ds ='20171011')
```
实际返回值为下面语句返回值，执行时丢失分区信息：
```
show table extended like 'test_users_dt' 
```
image

### PR DESCRIPTION
**Pull request by zhexuany**
### What problem does this PR solve? 
This PR closes #1330

### What is changed and how it works?
When we process `ShowCommand`, we first check the emptiness of `partitionSpec`. We append partition info if such spec is not empty. 

### Check List 

Tests 

tests will be added later.

### CODE REVIEW

**Comment by birdstorm** [comment]
can you add a test?

**Comment by zhexuany** [comment]
@birdstorm Yes, I was figuring out how to add a test. :(

**Comment by birdstorm** [comment]
> @birdstorm Yes, I was figuring out how to add a test. :(

You may refer to  https://github.com/pingcap/tispark/blob/0f5135c/core/src/test/scala/org/apache/spark/sql/catalyst/catalog/CatalogTestSuite.scala#L61-L108

**Comment by birdstorm** [comment]
need cherry-pick?

**Comment by zhexuany** [comment]
> need cherry-pick?

Yes, this PR need cherry pick.

**Comment by birdstorm** [comment]
@zhexuany please add tags to specify branches to cherry-pick to.

**Pull request merged**
