### PR TITLE
fix index scan bug

### PR DESCRIPTION
**Pull request by zhexuany**
### What problem does this PR solve? 
When we do index scan, we should not add required index data type. 

### What is changed and how it works?
Remove related code in double read case.

### Check List 

Tests 
 - Manual test (add detailed scripts or steps below)

Related changes
 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by zhexuany** [comment]
@birdstorm @marsishandsome PTAL

**Comment by marsishandsome** [comment]
cherry pick to release-2.1?

**Pull request merged**
