### PR TITLE
Add proposal issue type

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve? 
Add proposal issue type
I'd like to create proposal issue：Propose a solution for a feature, architecture change, etc. Act as a tracking issue and start point for the whole procedure: design, code, review, test, release. This might close a feature request issue but it's not required.

### CODE REVIEW

**Comment by shiyuhang0** [comment]
@zhangyangyu @xuanyu66 @birdstorm @sunxiaoguang PTAL

**Review by zhangyangyu — APPROVED** [review]

**Review by sunxiaoguang — APPROVED** [review]

**Pull request merged**
