### PR TITLE
Add health check timeout

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve? 

Add health check timeout to
- controller the timeout of health check in upstream client-java
-  controller the timeout of tiflash probe in tispark

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Review by zhangyangyu — APPROVED** [review]

**Review by xuanyu66 — APPROVED** [review]

**Comment by shiyuhang0** [comment]
part of https://github.com/pingcap/tispark/issues/2707

**Pull request merged**
