### PR TITLE
Fix retry bug

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve? 
we should not retry for some errors in the prewrite primary key.

This has been done in https://github.com/pingcap/tispark/pull/1768. But It was broken in https://github.com/pingcap/tispark/pull/1987

So, just recover what has been done in https://github.com/pingcap/tispark/pull/1768.

### CODE REVIEW

**Comment by shiyuhang0** [comment]
@birdstorm PTAL if this change will affect https://github.com/pingcap/tispark/pull/1987

**Review by xuanyu66 — APPROVED** [review]

**Pull request merged**
