### PR TITLE
Feature:  decode json to string

### PR DESCRIPTION
**Pull request by alex-lx**
Convert JSON from binary format to String format. see example below
```
scala>  spark.sql("select * from json_test where ").show
+-----+--------------------+
|   id|         person_desc|
+-----+--------------------+
|    1|{"authors":[{"fir...|
|    2|        {"abc":null}|
|30001|"12345678\n\"世界12...|
|30002|              "1234"|
|30003|{"abc":123,"efg":...|
+-----+--------------------+
```

### CODE REVIEW

**Comment by birdstorm** [comment]
Hi, @alex-lx. Please let me express my gratitude to your brilliant patch. 

I think you could add some tests concerning JSON types, you may refer to some existing tests in IssueTestSuite. I will start the review now.

**Comment by alex-lx** [comment]
@birdstorm, thanks for your review. I will add the test soon.

**Comment by alex-lx** [comment]
Hello, @birdstorm. Test added, Please take a look.

**Comment by alex-lx** [comment]
Sorry, I can‘t reproduce the failure in my environment. I think it may cause by the version of tidb. Would you mind if the test does not use `judge()` to compare with `jdbc`'s result but just compare to the corresponding literal string?

**Comment by birdstorm** [comment]
@alex-lx Of course, I will handle this test failure. Thanks again for your contribution.

**Comment by birdstorm** [comment]
Test fails due to https://github.com/pingcap/tidb/pull/7389

**Pull request merged**
