### PR TITLE
fix bit pushdown

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve? 
TiKV support bit push down in https://github.com/tikv/tikv/pull/11968. But it causes some tests of TiSpark fail. The following are the fail test
- Fix Bit Type default value bug
- Test Convert from java.lang.Short to BIT
- Test Convert from java.lang.Integer to BIT
- Test Convert from java.lang.Long to BIT

This pr fixes those tests. By the way, `Fix Bit Type default value bug` fails because of the TiKV bug. So, ignore it before TiKV fixes it

### CODE REVIEW

**Comment by shiyuhang0** [comment]
TiKV revert bit push down in https://github.com/tikv/tikv/pull/12030.
So, we needn't push down bit too.
But the bug exists actually, so just fix the bug.

**Comment by shiyuhang0** [comment]
PTAL @xuanyu66 @zhangyangyu @birdstorm

**Review by xuanyu66 — APPROVED** [review]

**Review by zhangyangyu — APPROVED** [review]

**Review by sunxiaoguang — APPROVED** [review]

**Pull request merged**
