### PR TITLE
[WIP] support Spark 3.1.1

### PR DESCRIPTION
**Pull request by Dieken**
### What problem does this PR solve?

Make TiSpark support Spark 3.1.1.

### What is changed and how it works?

Fixed some build failures due to Spark API changes.

### Check List

Tests

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change: NO
 - Has exported variable/fields change: NO
 - Has interface methods change: NO
 - Has persistent data change: NO

Side effects

 - Possible performance regression: NO
 - Increased code complexity: NO
 - Breaking backward compatibility: NO

Related changes

 - Need to cherry-pick to the release branch: NO
 - Need to update the documentation: YES
 - Need to update the `tidb-ansible` repository: NO
 - Need to be included in the release note: YES

### CODE REVIEW

**Comment by Dieken** [comment]
/run-all-tests

PLEASE DON'T MERGE!   This PR is just to make use of CI pipeline to verify this patch.

**Comment by marsishandsome** [comment]
nice work.
I have a similar PR https://github.com/pingcap/tispark/pull/2024

**Comment by Dieken** [comment]
> nice work.
> I have a similar PR #2024

Yes, I just found your work this noon,  thank you very much for your quick response!

I'll take your more complete code change,  this PR will be closed after the CI build passes,  the build is toooooo  slooooooow on my Macbook Pro :-D

Looking forward to your release of tispark-2.5.0!

**Pull request closed without merging**
