### PR TITLE
add Limitations

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve? 
https://github.com/pingcap/tispark/issues/2190
https://asktug.com/t/topic/302949
https://asktug.com/t/topic/302960

### What is changed and how it works?
change readme

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by shiyuhang0** [comment]
@sunxiaoguang @xuanyu66 @birdstorm PTAL

**Review by sunxiaoguang — APPROVED** [review]

**Comment by sunxiaoguang** [comment]
/run-idc_jenkins_ci_tispark/integration-test

**Pull request merged**
