### PR TITLE
reduce dependencias 

### PR DESCRIPTION
**Pull request by zhexuany**
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tispark/190)

### CODE REVIEW

**Comment by zhexuany** [comment]
17/12/30 11:40:00 WARN TestCase: Result: All tests done.
17/12/30 11:40:00 WARN TestCase: Result: Tests run: 1228  Tests succeeded: 351  Tests failed: 535  Tests skipped: 342

**Comment by birdstorm** [comment]
@zhexuany Why are there more test fails than previous?

**Comment by zhexuany** [comment]
17/12/30 21:50:52 WARN TestCase: Result: All tests done.
17/12/30 21:50:52 WARN TestCase: Result: Tests run: 21  Tests succeeded: 21  Tests failed: 0  Tests skipped: 0

17/12/30 21:59:09 WARN TestCase: Result: All tests done.
17/12/30 21:59:09 WARN TestCase: Result: Tests run: 1227  Tests succeeded: 828  Tests failed: 98  Tests skipped: 301

17/12/30 22:35:35 WARN TestCase: Result: All tests done.
17/12/30 22:35:35 WARN TestCase: Result: Tests run: 6841  Tests succeeded: 3766  Tests failed: 8  Tests skipped: 3067

**Comment by zhexuany** [comment]
@birdstorm PTAL

**Pull request merged**
