### PR TITLE
Fix test fail in TiDB release 4.0

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve? 
https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tispark_ghpr_integration_test/runs/703/nodes/105/steps/471/log/?start=0

`Test date pk clustered ` and `Test timestamp pk clustered` fail in the IT with TiDB release-4.0

### CODE REVIEW

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-4.0 pd=release-4.0 tiflash=release-4.0 tikv=release-4.0

**Review by xuanyu66 — APPROVED** [review]

**Review by birdstorm — APPROVED** [review]
LGTM

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-4.0 pd=release-4.0 tiflash=release-4.0 tikv=release-4.0

**Pull request merged**
