### PR TITLE
TISPARK-191 update README

### LINKED ISSUE #813: update TiSpark's README
```
./bin/spark-shell --jars /wherever-it-is/tispark-${version}-jar-with-dependencies.jar
```

above is wrong, the jar we built is actually `tispark-core-${version}-jar-with-dependencies.jar`

### PR DESCRIPTION
**Pull request by windtalker**
fix #813, fix misleading jar name in README

### CODE REVIEW

**Comment by birdstorm** [comment]
@windtalker please sign CLA, thx~

**Comment by zhexuany** [comment]
```

- Test Convert from java.lang.Double to ENUM *** FAILED ***

  java.sql.SQLException: Region is unavailable

  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)

  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)

  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)

  at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)

  at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)

  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2483)

  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2441)

  at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)

  at com.pingcap.tispark.datasource.BaseDataSourceTest.queryJDBC(BaseDataSourceTest.scala:213)

  at com.pingcap.tispark.datasource.BaseDataSourceTest.compareTiDBSelectWithJDBC(BaseDataSourceTest.scala:154)

  ...

- Test Convert from String to ENUM
``` 

ci reports above exception. It seems to be tidb's problem. @birdstorm Can we just merge this PR since it purely doc change.

**Comment by birdstorm** [comment]
> ```
> 
> - Test Convert from java.lang.Double to ENUM *** FAILED ***
> 
>   java.sql.SQLException: Region is unavailable
> 
>   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
> 
>   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
> 
>   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
> 
>   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
> 
>   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
> 
>   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2483)
> 
>   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2441)
> 
>   at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
> 
>   at com.pingcap.tispark.datasource.BaseDataSourceTest.queryJDBC(BaseDataSourceTest.scala:213)
> 
>   at com.pingcap.tispark.datasource.BaseDataSourceTest.compareTiDBSelectWithJDBC(BaseDataSourceTest.scala:154)
> 
>   ...
> 
> - Test Convert from String to ENUM
> ```
> 
> ci reports above exception. It seems to be tidb's problem. @birdstorm Can we just merge this PR since it purely doc change.

I AM trying to solve this via #814, so this PR will be blocked temporarily in order that we can make sure  the corresponding fix works.

**Comment by zhexuany** [comment]
Gotcha. So let's open and wait until ur fix works.

**Pull request merged**
