### PR TITLE
delete scala default value

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve? 
Set scala default value cause CI fail

### CODE REVIEW

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-4.0 pd=release-4.0 tiflash=release-4.0 tikv=release-4.0 profile=scala-2.11 profile=spark-2.3

**Review by xuanyu66 — APPROVED** [review]

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-4.0 pd=release-4.0 tiflash=release-4.0 tikv=release-4.0 profile=scala-2.11

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-4.0 pd=release-4.0 tiflash=release-4.0 tikv=release-4.0 profile=scala-2.11

**Review by zhangyangyu — APPROVED** [review]

**Pull request merged**
