### PR TITLE
change master version and add changelog to master

### PR DESCRIPTION
**Pull request by qidi1**
Signed-off-by: qidi1 <1083369179@qq.com>

### What problem does this PR solve? 
Add changelog.
Change version to 3.2.0-SNAPSHOT.

### CODE REVIEW

**Review by zhangyangyu — CHANGES_REQUESTED** [review]
There are some style problem in changelog, uppercase/lowercase, space, and use full word plz.

**Review by zhangyangyu — APPROVED** [review]

**Review by Daemonxiao — APPROVED** [review]

**Review by shiyuhang0 — APPROVED** [review]

**Review by shiyuhang0 — APPROVED** [review]

**Pull request merged**
