### PR TITLE
Add design doc

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve? 
https://github.com/pingcap/tispark/issues/2242 design doc

### CODE REVIEW

**Comment by shiyuhang0** [comment]
PTAL @zhangyangyu Do you have any suggestions for the structure and template of design doc?

**Comment by shiyuhang0** [comment]
@xuanyu66 @birdstorm PTAL. DSV2 support has finished, this design need be merged

**Review by xuanyu66 — APPROVED** [review]

**Review by sunxiaoguang — APPROVED** [review]
LGTM

**Pull request merged**
