### PR TITLE
fix ci run on tidb master branch

### PR DESCRIPTION
**Pull request by marsishandsome**
close https://github.com/pingcap/tispark/issues/892

remove assumption that auto increment step = 30000

because of this PR pingcap/tidb#10978

### CODE REVIEW

**Comment by marsishandsome** [comment]
@zhexuany @birdstorm PTAL

**Comment by birdstorm** [comment]
any comments or description about how this pr works?

**Comment by marsishandsome** [comment]
> any comments or description about how this pr works?

remove assumption that auto increment step = 30000
do not compare auto generated id

**Comment by birdstorm** [comment]
> > any comments or description about how this pr works?
> 
> remove assumption that auto increment step = 30000
> do not compare auto generated id

Noe that we do not check auto-gen, how to test its correctness in implementation?

**Comment by marsishandsome** [comment]
> > > any comments or description about how this pr works?
> > 
> > 
> > remove assumption that auto increment step = 30000
> > do not compare auto generated id
> 
> Noe that we do not check auto-gen, how to test its correctness in implementation?

@zhexuany will write a test design document, this PR only wants to fix failed ci.

**Pull request merged**
