### PR TITLE
ADD: license checker

### PR DESCRIPTION
**Pull request by xuanyu66**
### What problem does this PR solve? 

- Add license checker in order to check license automatically
- Fix the wrong license header

### CODE REVIEW

**Comment by xuanyu66** [comment]
@tisonkun Hello, sorry to disrupt you, would you please help me find out why this license checker always fail

**Comment by tisonkun** [comment]
@xuanyu66 because files you checked miss the license header. You can check from the error logs to find files doesn't meet the requirement.

https://github.com/pingcap/tispark/runs/5509671375?check_suite_focus=true

**Comment by tisonkun** [comment]
The license header is incorrect.

**Comment by tisonkun** [comment]
Check https://github.com/pingcap/tidb/pull/27198 for the reason. The license header is incorrect and copyed everywhere. You can do a global find and replace to fix it.

**Comment by xuanyu66** [comment]
@tisonkun thank you. It doesn't occur to me that license header is in correct

**Comment by xuanyu66** [comment]
@zhangyangyu @shiyuhang0 PLTA

**Review by shiyuhang0 — APPROVED** [review]

**Review by zhangyangyu — APPROVED** [review]

**Review by sunxiaoguang — APPROVED** [review]

**Pull request merged**
