### PR TITLE
MOD: remove unuseful tests

### PR DESCRIPTION
**Pull request by xuanyu66**
### What problem does this PR solve? 

These two tests are related to TiDB bugs.
  - https://github.com/pingcap/tidb/issues/18949
  - https://github.com/pingcap/tidb/issues/25099

Since we include these two tests, the integration test with TiDB 4.0.x  will not pass, which make tests unstable

### What is changed and how it works?

Delete these tests, since it's appropriate to test TiSpark bugs not TiDB bugs in tests.

### Check List 

Tests 

 - Integration test
 - needs-cherry-pick-2.4

### CODE REVIEW

**Comment by xuanyu66** [comment]
/run-all-tests tikv=release-4.0 tidb=release-4.0 pd=release-4.0

**Comment by xuanyu66** [comment]
@birdstorm @sunxiaoguang PTAL

**Review by sunxiaoguang — APPROVED** [review]
LGTM

**Comment by xuanyu66** [comment]
@sunxiaoguang could you please add label 'needs-cherry-pick-2.4'

**Comment by sunxiaoguang** [comment]
> @sunxiaoguang could you please add label 'needs-cherry-pick-2.4'

Label added

**Pull request merged**
