### PR TITLE
add field type on each expr

### PR DESCRIPTION
**Pull request by zhexuany**
### What problem does this PR solve? 
TiFlash's side is doing a stricter check. TiFlash requires expr, pushed down to it, providing FieldType. This PR addresses the problem.
### What is changed and how it works?
Adding FieldType for each expr. 

Tests 
 - Manual test (add detailed scripts or steps below)

### CODE REVIEW

**Comment by guliangliangatpingcap** [comment]
@zhexuany should release in tispark-2.2.1 ?

**Comment by zhexuany** [comment]
@guliangliangatpingcap Yep. It should be.

**Pull request merged**
