### PR TITLE
Add index related integration tests

### PR DESCRIPTION
**Pull request by birdstorm**
for #129

### CODE REVIEW

**Comment by ilovesoup** [comment]
What does this fix really do?

**Comment by birdstorm** [comment]
This pr adds index tests on all data types. Testing, not pushed yet.

**Comment by birdstorm** [comment]
when executing `./test_no_tpch.sh` which runs custom tests and index tests.

Result: Tests run: 1220  Tests succeeded: 725  Tests failed: 193  Tests skipped: 302

PTAL @ilovesoup

**Comment by birdstorm** [comment]
when executing ./test_dag.sh which runs dag tests.

Result: Tests run: 7311  Tests succeeded: 3749  Tests failed: 8  Tests skipped: 3554

**Pull request merged**
