### PR TITLE
TISPARK-11 Support LIKE function push down

### PR DESCRIPTION
**Pull request by birdstorm**
Fixes TISPARK-11

### CODE REVIEW

**Comment by birdstorm** [comment]
a preview of some plans
```
scala> spark.sql("select tp_varchar from full_data_type_table where tp_varchar LIKE '%a'").explain
== Physical Plan ==
TiDB CoprocessorRDD{[table: full_data_type_table] , Columns: [tp_varchar], Filter: [[tp_varchar] ENDS_WITH "a" reg: "%a"]}

scala> spark.sql("select tp_varchar from full_data_type_table where tp_varchar LIKE '%a%'").explain
== Physical Plan ==
TiDB CoprocessorRDD{[table: full_data_type_table] , Columns: [tp_varchar], Filter: [[tp_varchar] CONTAINS "a" reg: "%a%"]}

scala> spark.sql("select tp_varchar from full_data_type_table where tp_varchar LIKE 'a%a%'").explain
== Physical Plan ==
TiDB CoprocessorRDD{[table: full_data_type_table] , Columns: [tp_varchar], Filter: [[tp_varchar] LIKE "a%a%" reg: "a%a%"]}

scala> spark.sql("select tp_varchar from full_data_type_table where tp_varchar LIKE 'a%a'").explain
== Physical Plan ==
*Filter (length(tp_varchar#1) >= 2)
+- TiDB CoprocessorRDD{[table: full_data_type_table] , Columns: [tp_varchar], Filter: [[tp_varchar] ENDS_WITH "a" reg: "%a"], [[tp_varchar] STARTS_WITH "a" reg: "a%"]}
```

**Comment by Novemser** [comment]
Nice work!

**Comment by birdstorm** [comment]
TISPARK-11

**Comment by birdstorm** [comment]
TISPARK-11

**Comment by birdstorm** [comment]
TISPARK-11 #comment test

**Comment by birdstorm** [comment]
PTAL @ilovesoup

**Pull request merged**
