### PR TITLE
remove statement: TiSpark provides HTAP solution

### PR DESCRIPTION
**Pull request by zhangyangyu**
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Review by shiyuhang0 — APPROVED** [review]

**Review by xuanyu66 — APPROVED** [review]

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-6.1 tikv=release-6.1 pd=release-6.1

**Review by Daemonxiao — APPROVED** [review]

**Comment by xuanyu66** [comment]
/run-all-tests tidb=release-6.1 tikv=release-6.1 pd=release-6.1

**Comment by xuanyu66** [comment]
/run-all-tests tidb=release-6.1 tikv=release-6.1 pd=release-6.1

**Pull request merged**
