### PR TITLE
fix region split: region split key should be a vaild key

### PR DESCRIPTION
**Pull request by marsishandsome**
### What problem does this PR solve? 
fix region split: region split key should be a vaild key

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Review by birdstorm — APPROVED** [review]
LGTM

**Comment by flowbehappy** [comment]
I think the `next()` function is quite dangerous because it will generate a none exists key, which both TiFlash and TiDB cannot recognize.

**Comment by birdstorm** [comment]
> I think the `next()` function is quite dangerous because it will generate a none exists key, which both TiFlash and TiDB cannot recognize.

@flowbehappy  It is not. Generating a non-existing key should not be dangerous at all. On the contrary, we should never make an assumption that a region start/end key is decodable because the `SPLIT REGION` API does not check the key at all, and could be called by any other roles in the cluster. 

Also, there are quite a few scenarios where we need to use a non-existing key. e.g., when building a raw key range that is more than `A`, we should explicitly use `next()`.

**Pull request merged**
