### PR TITLE
Fix myDecimal bug and add codec test

### PR DESCRIPTION
**Pull request by Handora**
* Add codec unit tests for improving code coverage
* Fix myDecimal bug that causes out of Index error when enlarging the fraction

### CODE REVIEW

**Comment by birdstorm** [comment]
It seems that tests are failing. @Handora 

>[INFO] Running com.pingcap.tikv.codec.CodecTest
>[ERROR] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.078 s <<< FAILURE! - in com.pingcap.tikv.codec.CodecTest
>[ERROR] readNWriteDateTimeTest(com.pingcap.tikv.codec.CodecTest)  Time elapsed: 0.009 s  <<< FAILURE!
>org.junit.internal.ArrayComparisonFailure: arrays first differed at element [3]; expected:<-108> but was:<-107>
>	at com.pingcap.tikv.codec.CodecTest.readNWriteDateTimeTest(CodecTest.java:471)

Also if this PR is ready to review, you may request for review or tag this PR with `reviewable`

**Comment by Handora** [comment]
I have correct the error on timezone part

**Comment by birdstorm** [comment]
You might need to test #444 with this PR. So you could merge two PRs into one and edit corresponding title and description. @Handora

**Comment by Handora** [comment]
I think that they are two different parts, this one is focusing on codec
unit tests while the other is focusing on MyDecimal, they are separated.
And MyDecimal is still having some small bugs on fromDouble side and I am
implementing the part (for example: for the internal presentation like
1.2300003E5 and so on).

**Comment by birdstorm** [comment]
Yes, there are two parts here. 

* Fix MyDecimal
* Add Codec test

If you want to fix MyDecimal, you need to validate whether it is correctly fixed. Thus you need to either move MyDecimal tests into #444, or merge #444 with this PR.

**Pull request merged**
