### PR TITLE
Bump jackson-databind from 2.9.10.8 to 2.12.6.1 in /tikv-client

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve? 
https://github.com/pingcap/tispark/pull/2282

`jackson.annotations.version` needs to be changed too.

### CODE REVIEW

**Comment by shiyuhang0** [comment]
@zhangyangyu @xuanyu66 PTAL

**Review by zhangyangyu — APPROVED** [review]

**Review by xuanyu66 — APPROVED** [review]

**Review by sunxiaoguang — APPROVED** [review]

**Pull request merged**
