### PR TITLE
fix count(bit) push down

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve? 
Count(bit) can't push down before TiKV 6.0.0,

### CODE REVIEW

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-5.4 tikv=release-5.4 pd=release-5.4

**Review by xuanyu66 — APPROVED** [review]

**Review by zhangyangyu — APPROVED** [review]

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-5.0 tikv=release-5.0 pd=release-5.0

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-5.1 tikv=release-5.1 pd=release-5.1

**Pull request merged**
