### PR TITLE
MOD: update how to import TiSpark jars for version >= 2.0

### PR DESCRIPTION
**Pull request by xuanyu66**
### What problem does this PR solve? 
The description on how to import TiSpark jar was outdated, Since from version 2.0 Spark-wrapper has been introduced into the project.

### Check List 

Tests 

 - No code

Related changes

 - Need to update the documentation

### CODE REVIEW

**Review by birdstorm — APPROVED** [review]
LGTM

**Comment by shiyuhang0** [comment]
> form

typo

**Comment by xuanyu66** [comment]
@sunxiaoguang @birdstorm  Can someone merge this.
Someone has  met this issue already

**Comment by xuanyu66** [comment]
@sunxiaoguang @birdstorm  Can someone merge this.
Someone has  met this issue already

**Comment by xuanyu66** [comment]
> > form
> 
> typo

what?

**Comment by xuanyu66** [comment]
@sunxiaoguang @birdstorm  Can someone merge this.
Someone has  met this issue already.

**Comment by sunxiaoguang** [comment]
Why CodeQL failed for a PR that has document changes only?

**Comment by shiyuhang0** [comment]
> Why CodeQL failed for a PR that has document changes only?

It seems the fork repository has been deleted

**Comment by birdstorm** [comment]
force merged

**Comment by shiyuhang0** [comment]
./bin/spark-shell --jars /wherever-it-is/tispark-assembly-${tispark_version}.jar:/wherever-it-is/spark-wrapper-${spark_version}-${tispark_version}.jar

**Pull request merged**
