### PR TITLE
add Aggregates in TiDAGRequest (#2371) 

### PR DESCRIPTION
**Pull request by qidi1**
This is an automated cherry-pick of https://github.com/pingcap/tispark/pull/2371

## What problem does this PR solve?
Fix test SumPushDownSuite fail in TiDB release-4.0.

## How to solve
TiDAGRequest has aggregates and pushdownAggregates which have the same meaning.
TiDAGRequest only shows pushdownAggregates when explain, But TiSpark will not set aggregates into pushdownAggregates in `FetchHandleRDD`.

This pr will show aggregates in TiDAGRequest so that we can see the aggregates in `FetchHandleRDD`.
when `CoprocessorRDD`, we can see both the aggregates and pushdownAggregates

### CODE REVIEW

**Comment by shiyuhang0** [comment]
/run-all-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Review by shiyuhang0 — APPROVED** [review]

**Review by Daemonxiao — APPROVED** [review]

**Pull request merged**
