### PR TITLE
fix-CatalogTestSuite

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve? 
solve the problem in https://github.com/pingcap/tispark/issues/2210

### What is changed and how it works?
set  TiAuthorization.enableAuth to false after TiAuthIntegrationSuite finish
change `tidb_tispark_test` to `${dbPrefix}tispark_tes`

Related changes

 - Need to cherry-pick to the release branch if have the some problem

### CODE REVIEW

**Comment by shiyuhang0** [comment]
@birdstorm @sunxiaoguang PTAL

**Review by sunxiaoguang — APPROVED** [review]

**Pull request merged**
