### PR TITLE
refactor database random test framework

### PR DESCRIPTION
**Pull request by marsishandsome**
### What problem does this PR solve? 
 database random test needs refactor

### What is changed and how it works?
refactor database random test framework
- move test framework code to a new maven module `db-random-test` (other projects like `TiBigData` also need this test framework)
- add a base test class `com.pingcap.tispark.test.RandomTest`
- refactor existing random test cases
- fix problem: do not support generate data (unique) for primary key >= 2 columns

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Comment by marsishandsome** [comment]
@birdstorm PTAL

**Review by birdstorm — APPROVED** [review]
LGTM

**Pull request merged**
